language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - gabe3195@gmail.com

script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
    #SONARCLOUD
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=gabehh-github -Dsonar.login=$SONAR